package com.laros.domain;
// Generated 02-may-2018 20:18:06 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventDetail generated by hbm2java
 */
@Entity
@Table(name = "event_detail", catalog = "dblaros")
public class EventDetail implements java.io.Serializable {

	private int eventDetailId;
	private Event event;
	private BigDecimal costo;
	private String createdBy;
	private Date createdDate;
	private String duracionEvento;
	private String fechaInscripcionEvento;
	private String horariosEvento;
	private BigDecimal membresiaAnual;
	private String numeroParticipantes;
	private String updatedBy;
	private Date updatedDate;
	private Integer rowVersion;
	private BigDecimal membresiaAnual_1;

	public EventDetail() {
	}

	public EventDetail(int eventDetailId, Event event) {
		this.eventDetailId = eventDetailId;
		this.event = event;
	}

	public EventDetail(int eventDetailId, Event event, BigDecimal costo, String createdBy, Date createdDate,
			String duracionEvento, String fechaInscripcionEvento, String horariosEvento, BigDecimal membresiaAnual,
			String numeroParticipantes, String updatedBy, Date updatedDate, Integer rowVersion,
			BigDecimal membresiaAnual_1) {
		this.eventDetailId = eventDetailId;
		this.event = event;
		this.costo = costo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.duracionEvento = duracionEvento;
		this.fechaInscripcionEvento = fechaInscripcionEvento;
		this.horariosEvento = horariosEvento;
		this.membresiaAnual = membresiaAnual;
		this.numeroParticipantes = numeroParticipantes;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.rowVersion = rowVersion;
		this.membresiaAnual_1 = membresiaAnual_1;
	}

	@Id

	@Column(name = "event_detail_id", unique = true, nullable = false)
	public int getEventDetailId() {
		return this.eventDetailId;
	}

	public void setEventDetailId(int eventDetailId) {
		this.eventDetailId = eventDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@Column(name = "costo")
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "duracion_evento", length = 200)
	public String getDuracionEvento() {
		return this.duracionEvento;
	}

	public void setDuracionEvento(String duracionEvento) {
		this.duracionEvento = duracionEvento;
	}

	@Column(name = "fecha_inscripcion_evento", length = 200)
	public String getFechaInscripcionEvento() {
		return this.fechaInscripcionEvento;
	}

	public void setFechaInscripcionEvento(String fechaInscripcionEvento) {
		this.fechaInscripcionEvento = fechaInscripcionEvento;
	}

	@Column(name = "horarios_evento", length = 200)
	public String getHorariosEvento() {
		return this.horariosEvento;
	}

	public void setHorariosEvento(String horariosEvento) {
		this.horariosEvento = horariosEvento;
	}

	@Column(name = "membresiaAnual")
	public BigDecimal getMembresiaAnual() {
		return this.membresiaAnual;
	}

	public void setMembresiaAnual(BigDecimal membresiaAnual) {
		this.membresiaAnual = membresiaAnual;
	}

	@Column(name = "numero_participantes", length = 200)
	public String getNumeroParticipantes() {
		return this.numeroParticipantes;
	}

	public void setNumeroParticipantes(String numeroParticipantes) {
		this.numeroParticipantes = numeroParticipantes;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "row_version")
	public Integer getRowVersion() {
		return this.rowVersion;
	}

	public void setRowVersion(Integer rowVersion) {
		this.rowVersion = rowVersion;
	}

	@Column(name = "membresia_anual")
	public BigDecimal getMembresiaAnual_1() {
		return this.membresiaAnual_1;
	}

	public void setMembresiaAnual_1(BigDecimal membresiaAnual_1) {
		this.membresiaAnual_1 = membresiaAnual_1;
	}

}
