package com.laros.domain;
// Generated 02-may-2018 20:18:06 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventTopic generated by hbm2java
 */
@Entity
@Table(name = "event_topic", catalog = "dblaros")
public class EventTopic implements java.io.Serializable {

	private int eventTopicId;
	private Event event;
	private String createdBy;
	private Date createdDate;
	private String descripcion;
	private String status;
	private BigDecimal temaOrden;
	private String titulo;
	private String updatedBy;
	private Date updatedDate;
	private String url;
	private Integer rowVersion;

	public EventTopic() {
	}

	public EventTopic(int eventTopicId, Event event, String descripcion, String titulo, String url) {
		this.eventTopicId = eventTopicId;
		this.event = event;
		this.descripcion = descripcion;
		this.titulo = titulo;
		this.url = url;
	}

	public EventTopic(int eventTopicId, Event event, String createdBy, Date createdDate, String descripcion,
			String status, BigDecimal temaOrden, String titulo, String updatedBy, Date updatedDate, String url,
			Integer rowVersion) {
		this.eventTopicId = eventTopicId;
		this.event = event;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.descripcion = descripcion;
		this.status = status;
		this.temaOrden = temaOrden;
		this.titulo = titulo;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.url = url;
		this.rowVersion = rowVersion;
	}

	@Id

	@Column(name = "event_topic_id", unique = true, nullable = false)
	public int getEventTopicId() {
		return this.eventTopicId;
	}

	public void setEventTopicId(int eventTopicId) {
		this.eventTopicId = eventTopicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "descripcion", nullable = false, length = 600)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "tema_orden")
	public BigDecimal getTemaOrden() {
		return this.temaOrden;
	}

	public void setTemaOrden(BigDecimal temaOrden) {
		this.temaOrden = temaOrden;
	}

	@Column(name = "titulo", nullable = false, length = 200)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "row_version")
	public Integer getRowVersion() {
		return this.rowVersion;
	}

	public void setRowVersion(Integer rowVersion) {
		this.rowVersion = rowVersion;
	}

}
