package com.laros.domain;
// Generated 02-may-2018 20:18:06 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "dblaros")
public class Event implements java.io.Serializable {

	private int eventId;
	private EventType eventType;
	private String createdBy;
	private Date createdDate;
	private String destacadoHome;
	private String status;
	private String tituloEvento;
	private String tituloFooterEvento;
	private String updatedBy;
	private Date updatedDate;
	private String keyEvento;
	private Integer rowVersion;
	private Set<EventInformation> eventInformations = new HashSet<EventInformation>(0);
	private Set<EventDetail> eventDetails = new HashSet<EventDetail>(0);
	private Set<EventTopic> eventTopics = new HashSet<EventTopic>(0);

	public Event() {
	}

	public Event(int eventId, EventType eventType, String tituloEvento, String tituloFooterEvento, String keyEvento) {
		this.eventId = eventId;
		this.eventType = eventType;
		this.tituloEvento = tituloEvento;
		this.tituloFooterEvento = tituloFooterEvento;
		this.keyEvento = keyEvento;
	}

	public Event(int eventId, EventType eventType, String createdBy, Date createdDate, String destacadoHome,
			String status, String tituloEvento, String tituloFooterEvento, String updatedBy, Date updatedDate,
			String keyEvento, Integer rowVersion, Set<EventInformation> eventInformations,
			Set<EventDetail> eventDetails, Set<EventTopic> eventTopics) {
		this.eventId = eventId;
		this.eventType = eventType;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.destacadoHome = destacadoHome;
		this.status = status;
		this.tituloEvento = tituloEvento;
		this.tituloFooterEvento = tituloFooterEvento;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.keyEvento = keyEvento;
		this.rowVersion = rowVersion;
		this.eventInformations = eventInformations;
		this.eventDetails = eventDetails;
		this.eventTopics = eventTopics;
	}

	@Id

	@Column(name = "event_id", unique = true, nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_type_id", nullable = false)
	public EventType getEventType() {
		return this.eventType;
	}

	public void setEventType(EventType eventType) {
		this.eventType = eventType;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "destacado_home")
	public String getDestacadoHome() {
		return this.destacadoHome;
	}

	public void setDestacadoHome(String destacadoHome) {
		this.destacadoHome = destacadoHome;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "titulo_evento", nullable = false, length = 200)
	public String getTituloEvento() {
		return this.tituloEvento;
	}

	public void setTituloEvento(String tituloEvento) {
		this.tituloEvento = tituloEvento;
	}

	@Column(name = "titulo_footer_evento", nullable = false, length = 100)
	public String getTituloFooterEvento() {
		return this.tituloFooterEvento;
	}

	public void setTituloFooterEvento(String tituloFooterEvento) {
		this.tituloFooterEvento = tituloFooterEvento;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "key_evento", nullable = false, length = 100)
	public String getKeyEvento() {
		return this.keyEvento;
	}

	public void setKeyEvento(String keyEvento) {
		this.keyEvento = keyEvento;
	}

	@Column(name = "row_version")
	public Integer getRowVersion() {
		return this.rowVersion;
	}

	public void setRowVersion(Integer rowVersion) {
		this.rowVersion = rowVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<EventInformation> getEventInformations() {
		return this.eventInformations;
	}

	public void setEventInformations(Set<EventInformation> eventInformations) {
		this.eventInformations = eventInformations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<EventDetail> getEventDetails() {
		return this.eventDetails;
	}

	public void setEventDetails(Set<EventDetail> eventDetails) {
		this.eventDetails = eventDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<EventTopic> getEventTopics() {
		return this.eventTopics;
	}

	public void setEventTopics(Set<EventTopic> eventTopics) {
		this.eventTopics = eventTopics;
	}

}
