package com.laros.domain;
// Generated 02-may-2018 20:18:06 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EventType generated by hbm2java
 */
@Entity
@Table(name = "event_type", catalog = "dblaros")
public class EventType implements java.io.Serializable {

	private int eventTypeId;
	private String createdBy;
	private Date createdDate;
	private String nombre;
	private String status;
	private String updatedBy;
	private Date updatedDate;
	private String code;
	private Integer rowVersion;
	private Set<Event> events = new HashSet<Event>(0);

	public EventType() {
	}

	public EventType(int eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public EventType(int eventTypeId, String createdBy, Date createdDate, String nombre, String status,
			String updatedBy, Date updatedDate, String code, Integer rowVersion, Set<Event> events) {
		this.eventTypeId = eventTypeId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.nombre = nombre;
		this.status = status;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.code = code;
		this.rowVersion = rowVersion;
		this.events = events;
	}

	@Id

	@Column(name = "event_type_id", unique = true, nullable = false)
	public int getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(int eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "row_version")
	public Integer getRowVersion() {
		return this.rowVersion;
	}

	public void setRowVersion(Integer rowVersion) {
		this.rowVersion = rowVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventType")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
