package com.laros.domain;
// Generated 02-may-2018 20:18:06 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "dblaros")
public class Module implements java.io.Serializable {

	private int moduleId;
	private String code;
	private String helpUrl;
	private String menuLabel;
	private BigDecimal menuOrder;
	private String name;
	private String url;
	private String visible;
	private Integer parentModuleId;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Integer rowVersion;
	private Set<Permission> permissions = new HashSet<Permission>(0);

	public Module() {
	}

	public Module(int moduleId) {
		this.moduleId = moduleId;
	}

	public Module(int moduleId, String code, String helpUrl, String menuLabel, BigDecimal menuOrder, String name,
			String url, String visible, Integer parentModuleId, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, Integer rowVersion, Set<Permission> permissions) {
		this.moduleId = moduleId;
		this.code = code;
		this.helpUrl = helpUrl;
		this.menuLabel = menuLabel;
		this.menuOrder = menuOrder;
		this.name = name;
		this.url = url;
		this.visible = visible;
		this.parentModuleId = parentModuleId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.rowVersion = rowVersion;
		this.permissions = permissions;
	}

	@Id

	@Column(name = "module_id", unique = true, nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "help_url")
	public String getHelpUrl() {
		return this.helpUrl;
	}

	public void setHelpUrl(String helpUrl) {
		this.helpUrl = helpUrl;
	}

	@Column(name = "menu_label")
	public String getMenuLabel() {
		return this.menuLabel;
	}

	public void setMenuLabel(String menuLabel) {
		this.menuLabel = menuLabel;
	}

	@Column(name = "menu_order")
	public BigDecimal getMenuOrder() {
		return this.menuOrder;
	}

	public void setMenuOrder(BigDecimal menuOrder) {
		this.menuOrder = menuOrder;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "visible")
	public String getVisible() {
		return this.visible;
	}

	public void setVisible(String visible) {
		this.visible = visible;
	}

	@Column(name = "parent_module_id")
	public Integer getParentModuleId() {
		return this.parentModuleId;
	}

	public void setParentModuleId(Integer parentModuleId) {
		this.parentModuleId = parentModuleId;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "row_version")
	public Integer getRowVersion() {
		return this.rowVersion;
	}

	public void setRowVersion(Integer rowVersion) {
		this.rowVersion = rowVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Permission> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

}
